<?php
/**
 * Admin availability management page - Interactive Calendar UI
 */

if (!defined('ABSPATH')) {
    exit;
}

$db = HP_Booking_Database::get_instance();
$default_start = trim((string) $db->get_setting('working_hours_start', '08:00'));
$default_end   = trim((string) $db->get_setting('working_hours_end', '22:00'));
if ($default_start === '') $default_start = '08:00';
if ($default_end === '')   $default_end   = '22:00';
$time_slot_interval = intval($db->get_setting('time_slot_interval', 15));
if ($time_slot_interval < 1) $time_slot_interval = 15;
?>

<div class="wrap hp-availability-manager">
    <h1>📅 Availability Management</h1>
    <p class="description">Click on dates and times to block or unblock availability. Blocked times won't appear in the booking form.</p>
    
    <div class="hp-availability-container">
        <!-- Quick Actions -->
        <div class="hp-quick-actions">
            <h3>Quick Actions</h3>
            <div class="hp-action-buttons">
                <button type="button" class="button hp-action-btn" data-action="block-day">
                    🚫 Block Entire Day
                </button>
                <button type="button" class="button hp-action-btn" data-action="block-weekend">
                    🏖️ Block Weekend
                </button>
                <button type="button" class="button hp-action-btn" data-action="block-time-range">
                    ⏰ Block Time Range
                </button>
                <button type="button" class="button hp-action-btn" data-action="clear-selection">
                    ✨ Clear Selection
                </button>
            </div>
        </div>
        
        <!-- Calendar View -->
        <div class="hp-calendar-section">
            <div class="hp-calendar-header">
                <button type="button" class="button hp-nav-btn" id="hp-prev-month">← Previous</button>
                <h2 id="hp-current-month-year"></h2>
                <button type="button" class="button hp-nav-btn" id="hp-next-month">Next →</button>
            </div>
            
            <div class="hp-calendar-grid" id="hp-calendar-grid">
                <!-- Calendar will be generated by JavaScript -->
            </div>
        </div>
        
        <!-- Interactive Selection Panel (appears when date is clicked) -->
        <div class="hp-selection-panel" id="hp-selection-panel" style="display: none;">
            <h3>Time Selection</h3>
            <p class="hp-panel-hint">Click a date on the calendar, then pick time slots below or use a custom range.</p>
            <div class="hp-form-group">
                <label>Date:</label>
                <input type="text" id="hp-selected-date" readonly class="regular-text" />
            </div>
            <div class="hp-form-group hp-time-slots-wrap">
                <label>Click slots to select (or drag across multiple):</label>
                <p class="description" style="margin:4px 0 8px 0;">Grey = default blocked (outside <?php echo esc_html($default_start . '–' . $default_end); ?>). Green = extended (unblocked). Select grey + Unblock to extend; select available + Block to block.</p>
                <div class="hp-hours-warning" id="hp-hours-warning" style="display:none;"></div>
                <div id="hp-time-slots-container"><!-- populated by JS --></div>
                <input type="hidden" id="hp-selected-time" />
            </div>
            <div class="hp-form-group hp-custom-range-toggle">
                <label><input type="checkbox" id="hp-use-custom-range" /> Use custom time range instead</label>
            </div>
            <div class="hp-form-group hp-custom-range" id="hp-custom-range-wrap" style="display:none;">
                <label>Custom start &amp; end:</label>
                <div class="hp-custom-inputs">
                    <input type="time" id="hp-custom-start" class="regular-text" />
                    <span>to</span>
                    <input type="time" id="hp-custom-end" class="regular-text" />
                </div>
            </div>
            <div class="hp-form-group">
                <details class="hp-working-hours">
                    <summary>Default available range &amp; slot interval</summary>
                    <div class="hp-working-hours-body">
                        <div class="hp-custom-inputs">
                            <label>Default unblocked start <input type="time" id="hp-working-start" value="<?php echo esc_attr($default_start); ?>" /></label>
                            <label>Default unblocked end <input type="time" id="hp-working-end" value="<?php echo esc_attr($default_end); ?>" /></label>
                            <label>Slot interval
                                <select id="hp-working-interval">
                                    <?php foreach (array(5,10,15,20,30,60) as $i): ?>
                                        <option value="<?php echo esc_attr($i); ?>" <?php selected($time_slot_interval, $i); ?>><?php echo esc_html($i); ?> min</option>
                                    <?php endforeach; ?>
                                </select>
                            </label>
                        </div>
                        <div class="hp-working-hours-actions">
                            <button type="button" class="button" id="hp-apply-hours">Apply</button>
                            <button type="button" class="button button-primary" id="hp-save-hours">Save</button>
                            <span class="hp-working-hours-status" id="hp-working-hours-status" style="display:none;"></span>
                        </div>
                        <p class="description" style="margin-top:10px;">All 24 hours are shown. By default 08:00–20:00 are unblocked; you can block/unblock any time.</p>
                    </div>
                </details>
            </div>
            <form id="hp-block-form">
                <div class="hp-form-group">
                    <label for="hp-block-type">Block Type:</label>
                    <select id="hp-block-type" class="regular-text">
                        <option value="unavailable">Unavailable</option>
                        <option value="maintenance">Maintenance</option>
                        <option value="personal">Personal</option>
                    </select>
                </div>
                <div class="hp-form-group">
                    <label for="hp-block-reason">Reason (optional):</label>
                    <input type="text" id="hp-block-reason" class="regular-text" placeholder="e.g., Vehicle service, Day off" />
                </div>
                <div class="hp-form-actions">
                    <button type="submit" class="button button-primary">Block Time</button>
                    <button type="button" class="button hp-unblock-btn" id="hp-unblock-btn" style="display:none;">Unblock Selected</button>
                    <button type="button" class="button hp-cancel-btn">Cancel</button>
                </div>
            </form>
        </div>
        
        <!-- Active Blocks List -->
        <div class="hp-blocks-list">
            <h3>Active Blocks</h3>
            <div id="hp-blocks-container">
                <p>Loading blocks...</p>
            </div>
        </div>
    </div>
</div>

<style>
.hp-availability-manager {
    max-width: 1400px;
}

.hp-availability-container {
    display: grid;
    grid-template-columns: 1fr;
    gap: 20px;
    margin-top: 20px;
}

.hp-quick-actions {
    background: #fff;
    border: 1px solid #ccd0d4;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

.hp-quick-actions h3 {
    margin-top: 0;
    color: #0073aa;
}

.hp-action-buttons {
    display: flex;
    gap: 10px;
    flex-wrap: wrap;
}

.hp-action-btn {
    padding: 8px 16px;
    font-size: 14px;
}

.hp-calendar-section {
    background: #fff;
    border: 1px solid #ccd0d4;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

.hp-calendar-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
    padding-bottom: 15px;
    border-bottom: 2px solid #0073aa;
}

.hp-calendar-header h2 {
    margin: 0;
    font-size: 24px;
    color: #0073aa;
}

.hp-nav-btn {
    padding: 8px 16px;
}

.hp-calendar-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 8px;
    margin-top: 20px;
}

.hp-calendar-day-header {
    text-align: center;
    font-weight: 600;
    padding: 10px;
    background: #f5f5f5;
    color: #555;
    border-radius: 4px;
}

.hp-calendar-day {
    aspect-ratio: 1;
    border: 2px solid #ddd;
    border-radius: 8px;
    padding: 8px;
    cursor: pointer;
    transition: all 0.2s;
    background: #fff;
    position: relative;
    display: flex;
    flex-direction: column;
    min-height: 100px;
}

.hp-calendar-day:hover {
    border-color: #0073aa;
    background: #f0f8ff;
    transform: scale(1.02);
}

.hp-calendar-day.other-month {
    opacity: 0.3;
    cursor: not-allowed;
}

.hp-calendar-day.today {
    border-color: #00a32a;
    background: #e8f5e9;
}

.hp-calendar-day.selected {
    border-color: #0073aa;
    background: #0073aa;
    color: #fff;
}

.hp-calendar-day.has-blocks {
    border-color: #d63638;
}

.hp-calendar-day.has-bookings {
    border-color: #2271b1;
}

.hp-day-number {
    font-size: 18px;
    font-weight: 600;
    margin-bottom: 4px;
}

.hp-day-status {
    font-size: 11px;
    margin-top: auto;
    padding: 2px 4px;
    border-radius: 3px;
    text-align: center;
}

.hp-day-status.blocked {
    background: rgba(214, 54, 56, 0.2);
    color: #d63638;
}

.hp-day-status.booked {
    background: rgba(34, 113, 177, 0.2);
    color: #2271b1;
}

.hp-day-status.available {
    background: rgba(0, 163, 42, 0.2);
    color: #00a32a;
}

.hp-selection-panel {
    background: #fff;
    border: 2px solid #0073aa;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.15);
    position: sticky;
    top: 20px;
}

.hp-selection-panel h3 {
    margin-top: 0;
    color: #0073aa;
}

.hp-panel-hint {
    font-size: 13px;
    color: #666;
    margin: 0 0 15px 0;
}

.hp-time-slots-wrap label {
    display: block;
    margin-bottom: 8px;
}

#hp-time-slots-container {
    min-height: 120px;
}

.hp-hours-warning {
    padding: 10px 12px;
    border: 1px solid #dba617;
    background: #fff8e5;
    border-radius: 6px;
    color: #5b4a00;
    margin: 0 0 10px 0;
    font-size: 13px;
}

.hp-working-hours summary {
    cursor: pointer;
    font-weight: 600;
    color: #0073aa;
}

.hp-working-hours-body {
    margin-top: 12px;
}

.hp-working-hours-actions {
    display: flex;
    gap: 10px;
    align-items: center;
    margin-top: 12px;
    flex-wrap: wrap;
}

.hp-working-hours-status {
    font-size: 12px;
    color: #1d2327;
}

.hp-custom-range-toggle {
    margin-top: 12px;
}

.hp-custom-inputs {
    display: flex;
    align-items: center;
    gap: 10px;
    flex-wrap: wrap;
}

.hp-custom-inputs input[type="time"] {
    padding: 6px 10px;
}

.hp-unblock-btn {
    background: #d63638;
    color: #fff;
    border-color: #d63638;
}

.hp-unblock-btn:hover {
    background: #b32d2e;
    color: #fff;
    border-color: #b32d2e;
}

.hp-form-group {
    margin-bottom: 15px;
}

.hp-form-group label {
    display: block;
    margin-bottom: 5px;
    font-weight: 600;
    color: #555;
}

.hp-form-actions {
    display: flex;
    gap: 10px;
    margin-top: 20px;
}

.hp-blocks-list {
    background: #fff;
    border: 1px solid #ccd0d4;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

.hp-blocks-list h3 {
    margin-top: 0;
    color: #0073aa;
}

.hp-block-item {
    background: #f9f9f9;
    border: 1px solid #ddd;
    border-left: 4px solid #d63638;
    padding: 15px;
    margin-bottom: 10px;
    border-radius: 4px;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.hp-block-item.personal {
    border-left-color: #f0b849;
}

.hp-block-item.maintenance {
    border-left-color: #2271b1;
}

.hp-block-item.extension {
    border-left-color: #2e7d32;
}

.hp-block-info {
    flex: 1;
}

.hp-block-info strong {
    display: block;
    margin-bottom: 5px;
    color: #333;
}

.hp-block-info small {
    color: #666;
    display: block;
}

.hp-block-actions {
    display: flex;
    gap: 5px;
}

.hp-time-slots {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(70px, 1fr));
    gap: 6px;
    max-height: 220px;
    overflow-y: auto;
    padding: 4px 0;
}

.hp-time-slot {
    padding: 6px;
    text-align: center;
    border: 1px solid #ddd;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
    transition: all 0.2s;
    user-select: none;
    -webkit-user-select: none;
}

.hp-time-slot:hover {
    background: #f0f8ff;
    border-color: #0073aa;
}

.hp-time-slot.selected {
    background: #0073aa;
    color: #fff;
    border-color: #0073aa;
}

.hp-time-slot.blocked {
    background: #ffebee;
    color: #c62828;
    cursor: not-allowed;
    opacity: 0.6;
}

.hp-time-slot.booked {
    background: #e3f2fd;
    color: #1565c0;
    cursor: not-allowed;
}

.hp-time-slot.default-blocked {
    background: #eee;
    color: #888;
    cursor: pointer;
}

.hp-time-slot.extended {
    background: #e8f5e9;
    color: #2e7d32;
}

@media (min-width: 1200px) {
    .hp-availability-container {
        grid-template-columns: 2fr 1fr;
    }
    
    .hp-selection-panel {
        grid-column: 2;
        grid-row: 1 / 3;
    }
    
    .hp-blocks-list {
        grid-column: 1 / -1;
    }
}
</style>

<script>
jQuery(document).ready(function($) {
    var currentDate = new Date();
    var selectedDate = null;
    var selectedTimeSlots = [];
    var blocks = [];
    var extensions = [];
    var bookings = [];
    var dataReady = 0; // track when both async loads finish
    var isDragging = false;
    var dragMode = true; // true for selecting, false for deselecting
    var defaultStart = '<?php echo esc_js($default_start); ?>' || '08:00';
    var defaultEnd   = '<?php echo esc_js($default_end); ?>'   || '20:00';
    var timeSlotInterval = <?php echo (int) $time_slot_interval; ?> || 15;

    $(document).on('mouseup', function() { isDragging = false; });

    // ---- Bootstrap: load data, THEN render ----
    loadMonthData();

    // Navigation — reload data when month changes
    $('#hp-prev-month').on('click', function() {
        currentDate.setMonth(currentDate.getMonth() - 1);
        loadMonthData();
    });
    $('#hp-next-month').on('click', function() {
        currentDate.setMonth(currentDate.getMonth() + 1);
        loadMonthData();
    });

    // Quick Actions
    $('.hp-action-btn').on('click', function() { handleQuickAction($(this).data('action')); });

    // Block form and custom range
    $('#hp-block-form').on('submit', function(e) { e.preventDefault(); saveBlock(); });
    $('.hp-cancel-btn').on('click', function() { clearSelection(); });
    $('#hp-use-custom-range').on('change', function() { $('#hp-custom-range-wrap').toggle($(this).is(':checked')); });
    $('#hp-unblock-btn').on('click', function() { unblockSelected(); });
    $('#hp-apply-hours').on('click', function() { applyWorkingHours(false); });
    $('#hp-save-hours').on('click', function() { applyWorkingHours(true); });

    // =========================================================
    // Data loading — loads blocks + bookings, then re-renders
    // =========================================================
    function getMonthRange() {
        var y = currentDate.getFullYear(), m = currentDate.getMonth();
        var startDate = new Date(y, m, 1).toISOString().split('T')[0];
        var endDate   = new Date(y, m + 1, 0).toISOString().split('T')[0];
        return { start: startDate, end: endDate };
    }

    function loadMonthData() {
        dataReady = 0;
        var range = getMonthRange();

        // Load blocks
        $.get(phpBookingAdmin.ajaxUrl, {
            action: 'hp_get_availability_blocks',
            nonce: phpBookingAdmin.nonce,
            start_date: range.start,
            end_date: range.end
        }).done(function(r) {
            blocks = (r.success && r.data.blocks) ? r.data.blocks : [];
            extensions = (r.success && r.data.extensions) ? r.data.extensions : [];
            renderBlocksList();
            if (++dataReady >= 2) renderCalendar();
        }).fail(function() {
            blocks = [];
            extensions = [];
            if (++dataReady >= 2) renderCalendar();
        });

        // Load bookings for the entire month (date range)
        $.get(phpBookingAdmin.ajaxUrl, {
            action: 'hp_get_bookings',
            nonce: phpBookingAdmin.nonce,
            start_date: range.start,
            end_date: range.end,
            per_page: 200
        }).done(function(r) {
            bookings = (r.success && r.data.bookings) ? r.data.bookings : [];
            if (++dataReady >= 2) renderCalendar();
        }).fail(function() {
            bookings = [];
            if (++dataReady >= 2) renderCalendar();
        });

        // Render immediately with stale data so user sees the calendar grid
        renderCalendar();
    }

    // =========================================================
    // Calendar rendering
    // =========================================================
    function renderCalendar() {
        var year = currentDate.getFullYear(), month = currentDate.getMonth();
        var daysInMonth = new Date(year, month + 1, 0).getDate();
        var startingDay = new Date(year, month, 1).getDay();

        $('#hp-current-month-year').text(
            currentDate.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })
        );

        var dayNames = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
        var html = '';
        dayNames.forEach(function(d) { html += '<div class="hp-calendar-day-header">' + d + '</div>'; });

        for (var i = 0; i < startingDay; i++) {
            html += '<div class="hp-calendar-day other-month"></div>';
        }

        for (var day = 1; day <= daysInMonth; day++) {
            var dateStr = year + '-' + String(month + 1).padStart(2,'0') + '-' + String(day).padStart(2,'0');
            var isToday = isTodayDate(year, month, day);
            var dayBlocks   = getBlocksForDate(dateStr);
            var dayBookings = getBookingsForDate(dateStr);

            var cls = 'hp-calendar-day';
            if (isToday) cls += ' today';
            if (dayBlocks.length)   cls += ' has-blocks';
            if (dayBookings.length) cls += ' has-bookings';
            if (selectedDate === dateStr) cls += ' selected';

            var statusText = 'Available', statusClass = 'available';
            if (dayBlocks.length) {
                statusText = dayBlocks.length + ' block(s)';
                statusClass = 'blocked';
            } else if (dayBookings.length) {
                statusText = dayBookings.length + ' booking(s)';
                statusClass = 'booked';
            }

            html += '<div class="' + cls + '" data-date="' + dateStr + '">'
                  + '<div class="hp-day-number">' + day + '</div>'
                  + '<div class="hp-day-status ' + statusClass + '">' + statusText + '</div>'
                  + '</div>';
        }

        $('#hp-calendar-grid').html(html);
        $('.hp-calendar-day:not(.other-month)').on('click', function() {
            selectDate($(this).data('date'));
        });
    }

    function selectDate(date) {
        selectedDate = date;
        selectedTimeSlots = [];
        renderCalendar();
        showTimeSlots(date);
    }

    function showTimeSlots(date) {
        var dateObj = new Date(date + 'T00:00:00');
        $('#hp-selected-date').val(dateObj.toLocaleDateString('en-US', { weekday:'long', year:'numeric', month:'long', day:'numeric' }));
        $('#hp-selection-panel').show();
        $('#hp-use-custom-range').prop('checked', false);
        $('#hp-custom-range-wrap').hide();
        $('#hp-hours-warning').hide().text('');
        updateCustomTimePlaceholders(date);

        var slots = generateTimeSlots();
        var dateBlocks   = getBlocksForDate(date);
        var dateBookings = getBookingsForDate(date);
        var dateExtensions = getExtensionsForDate(date);

        if (!slots.length) {
            $('#hp-time-slots-container').html('<p class="hp-no-slots-msg">No time slots. Check the slot interval setting above.</p>');
            updateUnblockButton(date, dateBlocks, dateBookings, dateExtensions);
            return;
        }

        var slotsHtml = '<div class="hp-time-slots">';
        slots.forEach(function(slot) {
            var slotTime = slot + ':00';
            var blocked  = isTimeBlocked(date, slotTime, dateBlocks);
            var booked   = isTimeBooked(date, slotTime, dateBookings);
            var extended = isTimeExtended(date, slotTime, dateExtensions);
            var defaultBlocked = isTimeDefaultBlocked(slot);
            var sel      = selectedTimeSlots.indexOf(slot) > -1;
            var cls = 'hp-time-slot';
            if (blocked) cls += ' blocked';
            else if (booked) cls += ' booked';
            else if (defaultBlocked && !extended) cls += ' default-blocked';
            else if (extended) cls += ' extended';
            if (sel) cls += ' selected';
            slotsHtml += '<div class="' + cls + '" data-time="' + slot + '">' + slot + '</div>';
        });
        slotsHtml += '</div>';

        $('#hp-time-slots-container').html(slotsHtml);
        updateUnblockButton(date, dateBlocks, dateBookings, dateExtensions);

        $('.hp-time-slot:not(.blocked):not(.booked)')
            .on('mousedown', function(e) {
                isDragging = true;
                e.preventDefault();
                var time = $(this).data('time');
                dragMode = selectedTimeSlots.indexOf(time) === -1;
                setTimeSlotState(time, dragMode, this);
            })
            .on('mouseenter', function() {
                if (isDragging) {
                    var time = $(this).data('time');
                    setTimeSlotState(time, dragMode, this);
                }
            });
        $('.hp-time-slot.blocked:not(.booked), .hp-time-slot.default-blocked')
            .on('mousedown', function(e) {
                e.preventDefault();
                var time = $(this).data('time');
                var idx = selectedTimeSlots.indexOf(time);
                if (idx === -1) {
                    selectedTimeSlots.push(time);
                    selectedTimeSlots.sort();
                    $(this).addClass('selected');
                } else {
                    selectedTimeSlots.splice(idx, 1);
                    $(this).removeClass('selected');
                }
                updateUnblockButton(date, dateBlocks, dateBookings, dateExtensions);
            });
    }

    function updateCustomTimePlaceholders(date) {
        var slots = generateTimeSlots();
        if (slots.length) {
            $('#hp-custom-start').attr('min', slots[0]);
            $('#hp-custom-start').attr('max', slots[slots.length-1]);
            $('#hp-custom-end').attr('min', slots[0]);
            $('#hp-custom-end').attr('max', slots[slots.length-1]);
        }
    }

    function updateUnblockButton(date, dateBlocks, dateBookings, dateExtensions) {
        if (!selectedTimeSlots.length) {
            $('#hp-unblock-btn').hide();
            return;
        }
        dateExtensions = dateExtensions || [];
        var allBlocked = selectedTimeSlots.every(function(slot) {
            var slotTime = slot + ':00';
            return isTimeBlocked(date, slotTime, dateBlocks) && !isTimeBooked(date, slotTime, dateBookings);
        });
        var allDefaultBlocked = selectedTimeSlots.every(function(slot) {
            var slotTime = slot + ':00';
            return isTimeDefaultBlocked(slot) && !isTimeExtended(date, slotTime, dateExtensions) && !isTimeBooked(date, slotTime, dateBookings);
        });
        var show = allBlocked || allDefaultBlocked;
        $('#hp-unblock-btn').toggle(show).data('extend-mode', allDefaultBlocked && !allBlocked);
    }

    function setTimeSlotState(time, select, el) {
        var idx = selectedTimeSlots.indexOf(time);
        if (select && idx === -1) {
            selectedTimeSlots.push(time);
            selectedTimeSlots.sort();
            $(el).addClass('selected');
        } else if (!select && idx > -1) {
            selectedTimeSlots.splice(idx, 1);
            $(el).removeClass('selected');
        }
        if (selectedDate) {
            var dateBlocks = getBlocksForDate(selectedDate);
            var dateBookings = getBookingsForDate(selectedDate);
            var dateExtensions = getExtensionsForDate(selectedDate);
            updateUnblockButton(selectedDate, dateBlocks, dateBookings, dateExtensions);
        }
    }

    function generateTimeSlots() {
        var slots = [];
        var interval = parseInt(timeSlotInterval, 10);
        if (!interval || interval < 1) interval = 15;
        var sm = 0;
        var em = 24 * 60 - 1;
        for (var mins = sm; mins <= em; mins += interval) {
            var h = Math.floor(mins / 60);
            var m = mins % 60;
            if (h >= 24) break;
            slots.push(String(h).padStart(2,'0') + ':' + String(m).padStart(2,'0'));
        }
        return slots;
    }

    function parseHHMMToMinutes(s) {
        if (!s || typeof s !== 'string') return null;
        var m = s.match(/^(\d{2}):(\d{2})$/);
        if (!m) return null;
        var hh = parseInt(m[1], 10), mm = parseInt(m[2], 10);
        if (isNaN(hh) || isNaN(mm) || hh < 0 || hh > 23 || mm < 0 || mm > 59) return null;
        return (hh * 60) + mm;
    }

    function applyWorkingHours(saveToDb) {
        var st = $('#hp-working-start').val();
        var et = $('#hp-working-end').val();
        var iv = parseInt($('#hp-working-interval').val(), 10);
        if (!st || !et) {
            $('#hp-working-hours-status').show().text('Please set both Start and End.');
            return;
        }
        if (!iv || iv < 1) iv = 15;
        defaultStart = st;
        defaultEnd = et;
        timeSlotInterval = iv;
        $('#hp-working-hours-status').hide().text('');
        if (selectedDate) showTimeSlots(selectedDate);

        if (!saveToDb) return;
        $('#hp-working-hours-status').show().text('Saving…');
        $.post(phpBookingAdmin.ajaxUrl, {
            action: 'hp_save_availability_working_hours',
            nonce: phpBookingAdmin.nonce,
            working_hours_start: st,
            working_hours_end: et,
            time_slot_interval: iv
        }).done(function(r) {
            if (r && r.success) {
                $('#hp-working-hours-status').show().text('Saved.');
                setTimeout(function() { $('#hp-working-hours-status').fadeOut(200); }, 1200);
            } else {
                $('#hp-working-hours-status').show().text((r && r.data && r.data.message) ? r.data.message : 'Save failed.');
            }
        }).fail(function() {
            $('#hp-working-hours-status').show().text('Save failed.');
        });
    }

    // =========================================================
    // Quick Actions
    // =========================================================
    function handleQuickAction(action) {
        if (action === 'block-day' && selectedDate) {
            createBlock(selectedDate, defaultStart, defaultEnd, 'unavailable', 'Entire day blocked');
        } else if (action === 'block-day' && !selectedDate) {
            alert('Please select a day on the calendar first.');
        } else if (action === 'block-weekend') {
            var today = new Date();
            var dow = today.getDay();
            var daysToSat = (6 - dow) % 7 || 7;
            var sat = new Date(today); sat.setDate(today.getDate() + daysToSat);
            var sun = new Date(sat);   sun.setDate(sat.getDate() + 1);
            [sat, sun].forEach(function(d) {
                var ds = d.toISOString().split('T')[0];
                createBlock(ds, defaultStart, defaultEnd, 'personal', 'Weekend');
            });
        } else if (action === 'block-time-range') {
            if (selectedTimeSlots.length >= 2) {
                var st = selectedTimeSlots[0];
                var et = selectedTimeSlots[selectedTimeSlots.length - 1];
                var ep = et.split(':').map(Number);
                var nd = new Date(); nd.setHours(ep[0], ep[1] + 15, 0);
                var ets = String(nd.getHours()).padStart(2,'0') + ':' + String(nd.getMinutes()).padStart(2,'0');
                createBlock(selectedDate, st, ets, 'unavailable', 'Time range');
            } else {
                alert('Please select at least 2 time slots to create a time range.');
            }
        } else if (action === 'clear-selection') {
            clearSelection();
        }
    }

    // =========================================================
    // Save / Create / Delete blocks
    // =========================================================
    function saveBlock() {
        var st, et;
        if ($('#hp-use-custom-range').is(':checked')) {
            st = $('#hp-custom-start').val();
            et = $('#hp-custom-end').val();
            if (!st || !et) { alert('Please enter custom start and end times.'); return; }
            if (st >= et) { alert('End time must be after start time.'); return; }
        } else {
            if (!selectedDate || !selectedTimeSlots.length) {
                alert('Please select a date and at least one time slot.');
                return;
            }
            st = selectedTimeSlots[0];
            var ep = selectedTimeSlots[selectedTimeSlots.length - 1].split(':').map(Number);
            var interval = parseInt(timeSlotInterval, 10) || 15;
            var nd = new Date(); nd.setHours(ep[0], ep[1] + interval, 0);
            et = String(nd.getHours()).padStart(2,'0') + ':' + String(nd.getMinutes()).padStart(2,'0');
        }
        if (!selectedDate) { alert('Please select a date.'); return; }

        var dateExtensions = getExtensionsForDate(selectedDate);
        var allExtended = selectedTimeSlots.length && selectedTimeSlots.every(function(slot) {
            return isTimeDefaultBlocked(slot) && isTimeExtended(selectedDate, slot + ':00', dateExtensions);
        });

        if (allExtended) {
            var startDt = selectedDate + ' ' + (st.length === 5 ? st + ':00' : st);
            var endDt   = selectedDate + ' ' + (et.length === 5 ? et + ':00' : et);
            $.post(phpBookingAdmin.ajaxUrl, {
                action: 'hp_remove_extension',
                nonce: phpBookingAdmin.nonce,
                start_datetime: startDt,
                end_datetime: endDt
            }).done(function(r) {
                if (r.success) { alert('Extended time re-blocked.'); clearSelection(); loadMonthData(); }
                else { alert(r.data && r.data.message ? r.data.message : 'Error'); }
            }).fail(function() { alert('Request failed.'); });
        } else {
            $.post(phpBookingAdmin.ajaxUrl, {
                action: 'hp_block_availability',
                nonce: phpBookingAdmin.nonce,
                block_type: $('#hp-block-type').val(),
                start_datetime: selectedDate + ' ' + (st.length === 5 ? st + ':00' : st),
                end_datetime:   selectedDate + ' ' + (et.length === 5 ? et + ':00' : et),
                reason: $('#hp-block-reason').val() || ''
            }).done(function(r) {
                if (r.success) { alert('Time blocked!'); clearSelection(); loadMonthData(); }
                else { alert(r.data && r.data.message ? r.data.message : 'Error'); }
            }).fail(function() { alert('Request failed.'); });
        }
    }

    function unblockSelected() {
        if (!selectedDate || !selectedTimeSlots.length) {
            alert('Please select time slots to unblock.');
            return;
        }
        var st = selectedTimeSlots[0];
        var ep = selectedTimeSlots[selectedTimeSlots.length - 1].split(':').map(Number);
        var interval = parseInt(timeSlotInterval, 10) || 15;
        var nd = new Date(); nd.setHours(ep[0], ep[1] + interval, 0);
        var et = String(nd.getHours()).padStart(2,'0') + ':' + String(nd.getMinutes()).padStart(2,'0');
        var extendMode = $('#hp-unblock-btn').data('extend-mode');

        if (extendMode) {
            $.post(phpBookingAdmin.ajaxUrl, {
                action: 'hp_extend_availability',
                nonce: phpBookingAdmin.nonce,
                date: selectedDate,
                start_time: st,
                end_time: et
            }).done(function(r) {
                if (r.success) { alert('Times unblocked (extended availability)!'); clearSelection(); loadMonthData(); }
                else { alert(r.data && r.data.message ? r.data.message : 'Error'); }
            }).fail(function() { alert('Request failed.'); });
        } else {
            var startDt = selectedDate + ' ' + st + ':00';
            var endDt   = selectedDate + ' ' + et + ':00';
            $.post(phpBookingAdmin.ajaxUrl, {
                action: 'hp_unblock_by_range',
                nonce: phpBookingAdmin.nonce,
                start_datetime: startDt,
                end_datetime: endDt
            }).done(function(r) {
                if (r.success) { alert('Unblocked!'); clearSelection(); loadMonthData(); }
                else { alert(r.data && r.data.message ? r.data.message : 'Error'); }
            }).fail(function() { alert('Request failed.'); });
        }
    }

    function createBlock(date, startTime, endTime, type, reason) {
        $.post(phpBookingAdmin.ajaxUrl, {
            action: 'hp_block_availability',
            nonce: phpBookingAdmin.nonce,
            block_type: type,
            start_datetime: date + ' ' + startTime + ':00',
            end_datetime:   date + ' ' + endTime + ':00',
            reason: reason
        }).done(function(r) {
            if (r.success) { loadMonthData(); }
            else { alert('Error creating block'); }
        }).fail(function() { alert('Request failed.'); });
    }

    function deleteBlock(id) {
        $.post(phpBookingAdmin.ajaxUrl, {
            action: 'hp_unblock_availability',
            nonce: phpBookingAdmin.nonce,
            block_id: id
        }).done(function(r) {
            if (r.success) { loadMonthData(); }
            else { alert('Error deleting block'); }
        }).fail(function() { alert('Request failed.'); });
    }

    // =========================================================
    // Blocks list panel
    // =========================================================
    function renderBlocksList() {
        var html = '';
        var typeLabels = { 'unavailable':'Unavailable', 'maintenance':'Maintenance', 'personal':'Personal' };
        blocks.forEach(function(block) {
            var s = new Date(block.start_datetime.replace(' ','T'));
            var e = new Date(block.end_datetime.replace(' ','T'));
            html += '<div class="hp-block-item ' + block.block_type + '">'
                  + '<div class="hp-block-info">'
                  + '<strong>' + (typeLabels[block.block_type] || block.block_type) + '</strong>'
                  + '<small>' + s.toLocaleString() + ' &ndash; ' + e.toLocaleString() + '</small>'
                  + (block.reason ? '<small>Reason: ' + block.reason + '</small>' : '')
                  + '</div>'
                  + '<div class="hp-block-actions">'
                  + '<button class="button button-small hp-delete-block" data-id="' + block.id + '">Delete</button>'
                  + '</div></div>';
        });
        extensions.forEach(function(ex) {
            html += '<div class="hp-block-item extension">'
                  + '<div class="hp-block-info">'
                  + '<strong>Extended (unblocked)</strong>'
                  + '<small>' + ex.date + ' ' + ex.start_time + ' &ndash; ' + ex.end_time + '</small>'
                  + '</div>'
                  + '<div class="hp-block-actions">'
                  + '<button class="button button-small hp-remove-extension" data-date="' + ex.date + '" data-start="' + ex.start_time + '" data-end="' + ex.end_time + '">Remove</button>'
                  + '</div></div>';
        });
        if (!html) html = '<p>No active blocks or extended hours for this month.</p>';
        $('#hp-blocks-container').html(html);
        $('.hp-delete-block').on('click', function() {
            if (confirm('Delete this block?')) deleteBlock($(this).data('id'));
        });
        $('.hp-remove-extension').on('click', function() {
            var d = $(this).data('date'), st = $(this).data('start'), en = $(this).data('end');
            if (confirm('Remove this extended availability?')) removeExtension(d, st, en);
        });
    }

    function removeExtension(date, startTime, endTime) {
        var startDt = date + ' ' + (String(startTime).length === 5 ? startTime + ':00' : startTime);
        var endDt   = date + ' ' + (String(endTime).length === 5 ? endTime + ':00' : endTime);
        $.post(phpBookingAdmin.ajaxUrl, {
            action: 'hp_remove_extension',
            nonce: phpBookingAdmin.nonce,
            start_datetime: startDt,
            end_datetime: endDt
        }).done(function(r) {
            if (r.success) { loadMonthData(); }
            else { alert(r.data && r.data.message ? r.data.message : 'Error'); }
        }).fail(function() { alert('Request failed.'); });
    }

    // =========================================================
    // Helpers
    // =========================================================
    function getBlocksForDate(date) {
        return blocks.filter(function(b) { return b.start_datetime.split(' ')[0] === date; });
    }
    function getExtensionsForDate(date) {
        return extensions.filter(function(e) { return e.date === date; });
    }
    function isTimeDefaultBlocked(slot) {
        var m = parseHHMMToMinutes(slot);
        if (m === null) return true;
        var ds = parseHHMMToMinutes(defaultStart);
        var de = parseHHMMToMinutes(defaultEnd);
        if (ds === null || de === null) return false;
        return m < ds || m >= de;
    }
    function isTimeExtended(date, time, list) {
        var t = time.substring(0, 5);
        return list.some(function(e) {
            var es = String(e.start_time).substring(0, 5);
            var ee = String(e.end_time).substring(0, 5);
            return t >= es && t < ee;
        });
    }
    function getBookingsForDate(date) {
        return bookings.filter(function(b) {
            return b.pickup_datetime.split(' ')[0] === date && b.booking_status !== 'cancelled';
        });
    }
    function isTimeBlocked(date, time, list) {
        return list.some(function(b) {
            return time >= b.start_datetime.split(' ')[1].substring(0,5)
                && time <  b.end_datetime.split(' ')[1].substring(0,5);
        });
    }
    function isTimeBooked(date, time, list) {
        return list.some(function(b) {
            return b.pickup_datetime.split(' ')[1].substring(0,5) === time;
        });
    }
    function isTodayDate(y, m, d) {
        var t = new Date();
        return t.getFullYear() === y && t.getMonth() === m && t.getDate() === d;
    }
    function clearSelection() {
        selectedDate = null;
        selectedTimeSlots = [];
        $('#hp-selection-panel').hide();
        renderCalendar();
    }
});
</script>
